"""create_logs_tables

Revision ID: 6934fbabba4f
Revises: 
Create Date: 2025-10-16 15:07:06.585877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6934fbabba4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medication_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('side_effects', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('side_effect_severity', sa.Enum('NONE', 'MILD', 'MODERATE', 'SEVERE', 'CRITICAL', name='severitylevel'), nullable=True),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symptom_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'MILD', 'MODERATE', 'SEVERE', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('triggers', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('impact_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    # ### end Alembic commands ###